---
kind: pipeline
name: drone-gke-deployer

# steps:
# - name: build  
#   image: plugins/gcr
#   settings:
#     registry: eu.gcr.io
#     repo: moss-work/drone-gke-deployer
#     tags: latest
#     json_key:
#       from_secret: MW_PUSH_CREDS
#   when:
#     event: push
#     branch: master

steps:
- name: build  
  image: plugins/docker
  settings:
    username: mosstech
    password:
      from_secret: docker_hub_pass
    repo: mosstech/drone-gke-deployer
    auto_tag: true
  when:
    event: push
    branch: master

---
kind: signature
hmac: a5481f3d573cdc04d8f1aef251bbd9c82fd5daa67cb00a6cf7254b681dd214fe

...
