---
kind: pipeline
name: drone-gke-deployer

steps:
- name: build  
  image: plugins/docker
  settings:
    username: mosstech
    password:
      from_secret: DOCKER_REGISTRY_PASS
    repo: mosstech/drone-gke-deployer
    auto_tag: true
  when:
    event: push
    branch: master

---
kind: signature
hmac: a15039f68da9b5906b73ec08675a90f74af052a35bffb97ee162a1e44364f366

...
